language: python
python:
<<<<<<< HEAD

=======
>>>>>>> 6e5569b81ea0d6673d970fb7f879e41949da48f5
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
<<<<<<< HEAD
=======
  
>>>>>>> 6e5569b81ea0d6673d970fb7f879e41949da48f5
